import React, { useMemo, useRef, useState } from "react";

const sampleRows = [
  { date: "01 Sep", production: 4820, excavation: 6120, ash: 18.2, methane: 0.62 },
  { date: "02 Sep", production: 5150, excavation: 6380, ash: 17.6, methane: 0.71 },
  { date: "03 Sep", production: 4980, excavation: 6210, ash: 18.9, methane: 0.68 },
  { date: "04 Sep", production: 5360, excavation: 6540, ash: 17.1, methane: 0.77 },
  { date: "05 Sep", production: 5510, excavation: 6720, ash: 16.8, methane: 0.81 },
  { date: "06 Sep", production: 5630, excavation: 6810, ash: 17.4, methane: 0.74 },
  { date: "07 Sep", production: 5790, excavation: 6950, ash: 16.9, methane: 0.79 },
];

function Icon({ name, size = 20 }) {
  const p = {
    width: size, height: size, viewBox: "0 0 24 24", fill: "none",
    stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round", strokeLinejoin: "round"
  };
  const paths = {
    grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,
    upload: <><path d="M12 16V4"/><path d="m7 9 5-5 5 5"/><path d="M5 20h14"/></>,
    report: <><path d="M6 3h9l3 3v15H6z"/><path d="M14 3v4h4"/><path d="M9 13h6M9 17h6"/></>,
    geology: <><path d="m4 18 5-6 4 4 3-5 4 7"/><circle cx="8" cy="7" r="2"/><path d="M3 21h18"/></>,
    shield: <><path d="M12 3 20 6v5c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6z"/><path d="m9 12 2 2 4-5"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6V20h-2.6v-.1a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1A1.7 1.7 0 0 0 8 15a1.7 1.7 0 0 0-1.6-1H6v-2.6h.4A1.7 1.7 0 0 0 8 10a1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V5H15v.1a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.4V14h-.4a1.7 1.7 0 0 0-1.6 1z"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    download: <><path d="M12 4v11"/><path d="m7 11 5 5 5-5"/><path d="M5 20h14"/></>,
    spark: <><path d="m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7z"/><path d="m19 16 .7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7z"/></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>,
    arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,
  };
  return <svg {...p}>{paths[name]}</svg>;
}

function BarChart({ rows }) {
  const max = Math.max(...rows.map(r => r.production));
  return (
    <div className="chart">
      {rows.map((r, i) => (
        <div className="bar-col" key={i}>
          <div className="bar-value">{r.production}</div>
          <div className="bar" style={{height: `${Math.max(16, (r.production / max) * 150)}px`}} />
          <div className="bar-label">{r.date}</div>
        </div>
      ))}
    </div>
  );
}

function LineChart({ rows }) {
  const w = 700, h = 190, pad = 18;
  const vals = rows.map(r => r.methane);
  const min = Math.min(...vals) - 0.05, max = Math.max(...vals) + 0.05;
  const pts = vals.map((v, i) => {
    const x = pad + i * ((w - pad * 2) / (vals.length - 1));
    const y = h - pad - ((v - min) / (max - min)) * (h - pad * 2);
    return `${x},${y}`;
  }).join(" ");
  return (
    <svg className="line-chart" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">
      {[0,1,2,3].map(i => <line key={i} x1="0" x2={w} y1={35+i*42} y2={35+i*42} className="grid-line" />)}
      <polyline points={pts} className="line-path" />
      {vals.map((v,i) => {
        const [x,y] = pts.split(" ")[i].split(",");
        return <circle key={i} cx={x} cy={y} r="4" className="line-dot"/>;
      })}
    </svg>
  );
}

function makeReport(data, mine) {
  const production = data.reduce((a,b) => a + b.production, 0);
  const avgAsh = data.reduce((a,b) => a + b.ash, 0) / data.length;
  const avgMethane = data.reduce((a,b) => a + b.methane, 0) / data.length;
  const best = [...data].sort((a,b) => b.production-a.production)[0];
  return `CMPDI / CIL — AI-ASSISTED DAILY MINING REPORT
Mine: ${mine}
Report period: ${data[0].date} – ${data[data.length-1].date}
Generated by CoalSight AI

1. EXECUTIVE OVERVIEW
Total recorded production: ${production.toLocaleString()} tonnes.
Average daily production: ${Math.round(production/data.length).toLocaleString()} tonnes/day.
Peak production was ${best.production.toLocaleString()} tonnes on ${best.date}.

2. GEOLOGICAL & QUALITY OBSERVATIONS
Average ash content: ${avgAsh.toFixed(1)}%.
The production series shows a stable upward operating trend with normal day-to-day variation.
Quality observations should be validated against the latest laboratory assay and seam-wise sampling records before operational decisions.

3. SAFETY & RISK SCREENING
Average methane reading in the supplied sample: ${avgMethane.toFixed(2)}%.
No automatic emergency decision is made by this prototype. Readings approaching site-defined statutory/action thresholds should trigger verification by the responsible safety officer.

4. AI-GENERATED ACTIONABLE RECOMMENDATIONS
• Review the highest-production shifts for repeatable operating practices.
• Cross-check ash variation with seam/bench-wise geological records.
• Correlate methane trends with ventilation and shift logs.
• Keep daily production, quality and safety observations in a single auditable reporting workflow.

5. DATA QUALITY NOTE
This prototype converts structured demonstration data into a reporting workflow. Production, geology and safety decisions must be verified against authorized CMPDI/CIL source records.`;
}

export default function App() {
  const [page, setPage] = useState("dashboard");
  const [rows, setRows] = useState(sampleRows);
  const [mine, setMine] = useState("Gevra Open Cast Mine");
  const [report, setReport] = useState("");
  const [generating, setGenerating] = useState(false);
  const [fileName, setFileName] = useState("Demo dataset loaded");
  const [query, setQuery] = useState("");
  const fileRef = useRef(null);

  const stats = useMemo(() => {
    const production = rows.reduce((a,b) => a+b.production, 0);
    return {
      production,
      avg: Math.round(production / rows.length),
      ash: rows.reduce((a,b)=>a+b.ash,0)/rows.length,
      methane: rows.reduce((a,b)=>a+b.methane,0)/rows.length
    };
  }, [rows]);

  const generate = () => {
    setGenerating(true);
    setTimeout(() => {
      setReport(makeReport(rows, mine));
      setGenerating(false);
      setPage("reports");
    }, 900);
  };

  const loadDemo = () => {
    setRows(sampleRows);
    setFileName("CMPDI_Demo_Mining_Data.csv");
  };

  const parseCSV = (text) => {
    const lines = text.trim().split(/\r?\n/).filter(Boolean);
    if (lines.length < 2) return;
    const headers = lines[0].split(",").map(x => x.trim().toLowerCase());
    const find = (names) => headers.findIndex(h => names.some(n => h.includes(n)));
    const iProd = find(["production","coal","output"]);
    const iExc = find(["excavation","exc"]);
    const iAsh = find(["ash"]);
    const iMeth = find(["methane","ch4"]);
    const iDate = find(["date","day"]);
    const parsed = lines.slice(1).map((line, idx) => {
      const c = line.split(",").map(x => x.trim());
      return {
        date: c[iDate >= 0 ? iDate : 0] || `Day ${idx+1}`,
        production: Number(c[iProd]) || 0,
        excavation: Number(c[iExc]) || 0,
        ash: Number(c[iAsh]) || 0,
        methane: Number(c[iMeth]) || 0,
      };
    }).filter(r => r.production || r.excavation || r.ash || r.methane);
    if (parsed.length) {
      setRows(parsed.slice(-12));
      setFileName("Uploaded CSV dataset");
    }
  };

  const onFile = (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setFileName(f.name);
    const reader = new FileReader();
    reader.onload = ev => parseCSV(String(ev.target.result));
    reader.readAsText(f);
  };

  const downloadReport = () => {
    const blob = new Blob([report || makeReport(rows, mine)], {type:"text/plain;charset=utf-8"});
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${mine.replaceAll(" ","_")}_AI_Report.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const printReport = () => {
    const text = report || makeReport(rows, mine);
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<html><head><title>CoalSight AI Report</title><style>body{font-family:Arial;max-width:850px;margin:40px auto;line-height:1.6;white-space:pre-wrap}h1{font-size:22px}</style></head><body>${text.replaceAll("&","&amp;").replaceAll("<","&lt;")}</body></html>`);
    w.document.close(); w.focus(); w.print();
  };

  const nav = [
    ["dashboard","Dashboard","grid"],["intake","Data Intake","upload"],["reports","AI Reports","report"],["geology","Geological Insights","geology"],["safety","Safety Monitor","shield"]
  ];

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">⛏</div>
          <div><strong>CoalSight</strong><span>AI Mining Intelligence</span></div>
        </div>
        <div className="side-label">WORKSPACE</div>
        <nav>{nav.map(([id,label,icon]) =>
          <button key={id} className={page===id?"nav-item active":"nav-item"} onClick={()=>setPage(id)}>
            <Icon name={icon}/><span>{label}</span>
          </button>
        )}</nav>
        <div className="side-bottom">
          <div className="system-card"><span className="pulse"></span><div><b>System Online</b><small>Demo environment</small></div></div>
          <button className="nav-item"><Icon name="settings"/><span>Settings</span></button>
        </div>
      </aside>

      <main className="main">
        <header className="topbar">
          <div className="mobile-brand"><button onClick={()=>document.body.classList.toggle("menu-open")}><Icon name="menu"/></button><b>CoalSight AI</b></div>
          <div className="crumb"><span>Operations</span><b>/</b><strong>{nav.find(x=>x[0]===page)?.[1]}</strong></div>
          <div className="top-actions">
            <div className="search"><Icon name="search" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reports, mines..." /></div>
            <button className="icon-btn"><Icon name="bell"/></button>
            <div className="avatar">PS</div>
          </div>
        </header>

        <section className="content">
          {page === "dashboard" && <>
            <div className="hero">
              <div><div className="eyebrow"><span className="status-dot"></span> AI OPERATIONS CENTER</div><h1>Mining intelligence, <em>simplified.</em></h1><p>Convert field observations and production data into structured, decision-ready mining reports.</p></div>
              <button className="primary-btn" onClick={()=>setPage("intake")}><Icon name="upload" size={18}/> Import Mine Data <Icon name="arrow" size={17}/></button>
            </div>

            <div className="mine-row">
              <div><span>ACTIVE ASSET</span><select value={mine} onChange={e=>setMine(e.target.value)}><option>Gevra Open Cast Mine</option><option>Korba Mining Area</option><option>Singrauli Coalfield</option><option>Talcher Coalfield</option></select></div>
              <div className="data-badge">● Live prototype data <small>{fileName}</small></div>
            </div>

            <div className="kpi-grid">
              <Kpi title="Production" value={`${stats.production.toLocaleString()}`} unit="tonnes" change="+8.4%" icon="⛏" />
              <Kpi title="Avg. Daily Output" value={stats.avg.toLocaleString()} unit="t/day" change="+5.1%" icon="◈" />
              <Kpi title="Avg. Ash Content" value={stats.ash.toFixed(1)} unit="%" change="-2.3%" good icon="◇" />
              <Kpi title="Methane Index" value={stats.methane.toFixed(2)} unit="%" change="Normal" good icon="◉" />
            </div>

            <div className="grid-2">
              <Panel title="Production Performance" subtitle="7-day recorded production">
                <BarChart rows={rows.slice(-7)} />
              </Panel>
              <Panel title="Methane Trend" subtitle="Monitoring sample • % by volume">
                <LineChart rows={rows.slice(-7)} />
                <div className="legend"><span><i className="dot"></i>Observed methane</span><span className="threshold">Site threshold: verify locally</span></div>
              </Panel>
            </div>

            <div className="grid-3">
              <Panel title="AI Insight" icon="spark">
                <div className="insight"><div className="ai-icon"><Icon name="spark"/></div><div><b>Production trend is positive</b><p>Recorded output is trending upward across the sample. Review the highest-output shifts for repeatable operating practices.</p><button onClick={generate} className="text-btn">Generate detailed report <Icon name="arrow" size={15}/></button></div></div>
              </Panel>
              <Panel title="Data Coverage">
                <div className="coverage"><strong>{rows.length}</strong><span>records analyzed</span><div className="progress"><i style={{width:"86%"}}></i></div><small>Production • Quality • Safety</small></div>
              </Panel>
              <Panel title="Safety Status">
                <div className="safe-card"><div className="safe-check">✓</div><div><b>Monitoring active</b><p>No automatic emergency decision is made by this prototype.</p></div></div></Panel>
            </div>
          </>}

          {page === "intake" && <PageTitle title="Data Intake" subtitle="Bring production, geological and safety observations into one reporting workflow." action={<button className="primary-btn" onClick={generate}><Icon name="spark"/> Analyze with AI</button>}>
            <div className="intake-grid">
              <div className="upload-card">
                <div className="upload-icon"><Icon name="upload" size={28}/></div>
                <h3>Upload mine dataset</h3><p>CSV files are supported in this prototype.</p>
                <input ref={fileRef} type="file" accept=".csv,text/csv" onChange={onFile} hidden/>
                <button className="secondary-btn" onClick={()=>fileRef.current?.click()}>Choose CSV file</button>
                <button className="link-btn" onClick={loadDemo}>Use demo dataset</button>
                <div className="file-chip">✓ {fileName}</div>
              </div>
              <div className="form-card">
                <label>Mine / Project<select value={mine} onChange={e=>setMine(e.target.value)}><option>Gevra Open Cast Mine</option><option>Korba Mining Area</option><option>Singrauli Coalfield</option><option>Talcher Coalfield</option></select></label>
                <label>Reporting context<textarea placeholder="Add field observations, shift notes, equipment issues or geological remarks...">Sector 4 inspection completed. Conveyor line inspected. Production remained stable. Minor delay observed during belt maintenance.</textarea></label>
                <div className="mini-info"><b>AI pipeline</b><span>Data validation → trend detection → risk screening → structured report</span></div>
              </div>
            </div>
            <div className="table-card"><div className="table-head"><div><h3>Imported Records</h3><p>{rows.length} records currently available for analysis</p></div><button className="secondary-btn" onClick={loadDemo}>Reset demo</button></div><DataTable rows={rows}/></div>
          </PageTitle>}

          {page === "reports" && <PageTitle title="AI Reports" subtitle="Structured reporting output generated from the current mine dataset." action={<div className="btn-row"><button className="secondary-btn" onClick={printReport}>Print / Save PDF</button><button className="primary-btn" onClick={downloadReport}><Icon name="download"/> Download Report</button></div>}>
            {!report ? <div className="empty-report"><div className="ai-icon big"><Icon name="spark" size={30}/></div><h3>No report generated yet</h3><p>Analyze the current dataset to create a structured CMPDI/CIL-style report.</p><button className="primary-btn" onClick={generate}>Generate AI Report</button></div> :
            <div className="report-layout"><div className="report-paper"><div className="report-head"><div><span className="eyebrow">COALSIGHT AI • REPORT</span><h2>Daily Mining Intelligence Report</h2><p>{mine}</p></div><div className="report-seal">AI<br/>ASSISTED</div></div><pre>{report}</pre><div className="report-foot">Prototype output • Verify operational decisions against authorized mine records and statutory procedures.</div></div><div className="report-side"><div className="side-stat"><span>Records</span><b>{rows.length}</b></div><div className="side-stat"><span>Avg production</span><b>{stats.avg.toLocaleString()} <small>t/day</small></b></div><div className="side-stat"><span>Avg methane</span><b>{stats.methane.toFixed(2)}%</b></div><button className="secondary-btn full" onClick={()=>setPage("intake")}>Update dataset</button></div></div>}
          </PageTitle>}

          {page === "geology" && <PageTitle title="Geological Insights" subtitle="A focused view for geological and quality observations.">
            <div className="geology-grid"><div className="strata"><div className="mine-map"><div className="map-grid"></div><div className="seam s1">SEAM A</div><div className="seam s2">SEAM B</div><div className="seam s3">SEAM C</div><div className="drill d1"></div><div className="drill d2"></div><span className="map-label">Conceptual mine section</span></div></div>
            <div className="geo-cards"><Geo title="Average Ash" value={`${stats.ash.toFixed(1)}%`} text="Quality indicator across imported records."/><Geo title="Best Output Day" value={`${Math.max(...rows.map(r=>r.production)).toLocaleString()} t`} text="Peak production in current dataset."/><Geo title="Quality Watch" value="Stable" text="Validate seam-wise laboratory results before decisions."/></div></div>
            <div className="table-card"><div className="table-head"><div><h3>Quality & Production Matrix</h3><p>Current imported observations</p></div></div><DataTable rows={rows} geology/></div>
          </PageTitle>}

          {page === "safety" && <PageTitle title="Safety Monitor" subtitle="Prototype safety screening using the imported methane and operating observations.">
            <div className="safety-hero"><div className="safe-ring">✓</div><div><span className="eyebrow">CURRENT STATUS</span><h2>Monitoring active</h2><p>Average methane in the current sample is <b>{stats.methane.toFixed(2)}%</b>. This screen is an analytical aid, not an emergency control system.</p></div></div>
            <div className="grid-3"><Panel title="Methane Average"><div className="big-number">{stats.methane.toFixed(2)}<small>%</small></div><p className="muted">Across {rows.length} records</p></Panel><Panel title="Trend"><div className="trend-word">Stable</div><p className="muted">Review ventilation and shift logs alongside sensor records.</p></Panel><Panel title="Recommended Action"><div className="action-note"><b>Verify + correlate</b><p>Compare sensor readings with authorized site thresholds, ventilation logs and shift reports.</p></div></Panel></div>
          </PageTitle>}
        </section>
      </main>
    </div>
  );
}

function Kpi({title,value,unit,change,good,icon}) {
  return <div className="kpi"><div className="kpi-top"><span className="kpi-icon">{icon}</span><span className={good?"change good":"change"}>{change}</span></div><div className="kpi-value">{value}<small>{unit}</small></div><div className="kpi-title">{title}</div></div>
}
function Panel({title,subtitle,children,icon}) { return <div className="panel"><div className="panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{icon&&<Icon name={icon}/>}</div>{children}</div> }
function PageTitle({title,subtitle,action,children}) { return <><div className="page-title"><div><div className="eyebrow">COALSIGHT AI</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>{children}</> }
function DataTable({rows,geology=false}) { return <div className="data-table-wrap"><table><thead><tr><th>Date</th><th>Production (t)</th><th>Excavation (t)</th><th>Ash (%)</th><th>Methane (%)</th>{geology&&<th>Quality</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.production.toLocaleString()}</td><td>{r.excavation.toLocaleString()}</td><td>{r.ash.toFixed(1)}</td><td><span className="metric-pill">{r.methane.toFixed(2)}</span></td>{geology&&<td><span className="quality-pill">Stable</span></td>}</tr>)}</tbody></table></div> }
function Geo({title,value,text}) { return <div className="geo-card"><span>{title}</span><b>{value}</b><p>{text}</p></div> }
